# Site settings
theme: jekyll-theme-cayman
title: Scottish Country Dance Quickstart
author:
  name: Christoph Trautwein
  url: https://github.com/trautw
  twitter_username: trautw
  github_username:  trautw
  email: ch.trautwein@bmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hintergrund Infos zu meinem BMW E36 320i
tagline: > # this means to ignore newlines until "baseurl:"
  Hintergrund Infos zu meinem BMW E36 320i
baseurl: "/SCD-Quickstart" # the subpath of your site, e.g. /blog/
url: "https://trautw.github.io" # the base hostname & protocol for your site

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
